market_knowledge/config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  get "/properties/filter", to: "properties#filter"
  get "properties/search", to: "properties#search"

  get "/leases/filter", to: "leases#filter"
  get "/leases/search", to: "leases#search"

  resources :users
  resources :properties do
    collection {post :import}
  end
  resources :leases do
    collection {post :import}
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

market_knowledge/app/models/property.rb
class Property < ApplicationRecord
    has_many :leases, :dependent => :destroy
    validates :property_name, :street, :city, presence: true

  # Generate a CSV File of All Property Records
  def self.to_csv(fields = column_names, options={})
    CSV.generate(options) do |csv|      
            csv << fields
            all.each do |property|
                csv << property.attributes.values_at(*fields)
            end
        end
    end

  # Import CSV, Find or Create Property by its property_name.
  # Update the record.
  def self.import(file)
    if file == nil

    else
      CSV.foreach(file.path, headers: true) do |row|
        property_hash = row.to_hash
        @property = Property.where(:property_name => property_hash["property_name"], :street => property_hash["street"], :city => property_hash["city"]).first_or_create do |property|
          property.year_built = property_hash["year_built"]
          property.remodel_year = property_hash["remodel_year"]
          property.gross_bldg_area = property_hash["gross_bldg_area"]
          property.foundation_area = property_hash["foundation_area"]
          property.num_stories = property_hash["num_stories"]
          property.net_lease_area = property_hash["net_lease_area"]
          property.bldg_class = property_hash["bldg_class"]
          property.business_park = property_hash["business_park"]
          property.submarket = property_hash["submarket"]
          property.landlord_broker_company = property_hash["landlord_broker_company"]
          property.bldg_owner = property_hash["bldg_owner"]
          property.property_manager = property_hash["property_manager"]
          property.quoted_rate = property_hash["quoted_rate"]
          property.nnn = property_hash["nnn"]
          property.electric = property_hash["electric"]
        end
      end
    end
  end

  def self.search(search)
    if search
      if search != ""
        #would like to build to accept partial matches "contains"
        @properties = Property.where(property_name: search)
      else
        @properties = Property.all
      end
    else
      @properties = Property.all
    end
  end

  def self.filter(filter)
    type = filter.keys[0]
    value = filter[type]
    case type
      when ""
        @properties = Property.all
      when "submarket"
        @properties = Property.where(submarket: value)
      else
        @properties = Property.all
    end
  end

end

market_knowledge/app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  
    def show
      @property = Property.find(params[:id])
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @property}
      end
    end
  
    def index
      @properties = Property.all
      respond_to do |format|
        format.html
        format.csv { send_data @properties.to_csv(['property_name'])}
      end   
    end

    def search
      @properties = Property.search(params[:search])
      render :index
    end

    def filter
      @properties = Property.filter(params[:property])
      render :index 
    end

    def import
      Property.import(params[:file])
      # need to handle failures
      redirect_to properties_url
    end
  
    def new
      @property = Property.new
      @submarkets = Submarket.all
    end
  
    def create
      @property = Property.new(property_params)
      if @property.save
      render :show
      else
        @submarkets = Submarket.all
        render :new
      end
    end
  
    def edit
      @property = Property.find(params[:id])
      @submarkets = Submarket.all
    end
  
    def update
      @property = Property.find(params[:id])
      if @property.update(property_params)
        redirect_to @property
      else
        render :edit
      end
    end
  
    def destroy
      @property = Property.find(params[:id])
      @property.destroy
      redirect_to properties_path
    end
  
  private
  
    def property_params
      params.require(:property).permit(:property_name, :street, :city, :year_built, :remodel_year, :gross_bldg_area, :foundation_area, :num_stories, :net_lease_area, :bldg_class, :business_park, :submarket, :landlord_broker_company, :bldg_owner, :property_manager, :quoted_rate, :nnn, :electric)
    end
  
  end

market_knowledge/app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>

<% if @property.errors.any? %>
  <div>
    <h2>There were some errors:</h2>

    <ul>
      <% @property.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div>
    <%= f.label :property_name, "Building Name" %><br>
    <%= f.text_field :property_name %>
  </div>

  <div>
    <%= f.label :street, "Street" %><br>
    <%= f.text_field :street %>
  </div>

  <div>
    <%= f.label :city, "City" %><br>
    <%= f.text_field :city %>
  </div>

  <div>
    <%= f.label :year_built, "Year Built" %><br>
    <%= f.text_field :year_built %>
  </div>

  <div>
    <%= f.label :remodel_year, "Remodel Year" %><br>
    <%= f.text_field :remodel_year %>
  </div>

  <div>
    <%= f.label :gross_bldg_area, "Gross Building Area" %><br>
    <%= f.text_field :gross_bldg_area %>
  </div>

  <div>
    <%= f.label :foundation_area, "Foundation Area" %><br>
    <%= f.text_field :foundation_area %>
  </div>

  <div>
    <%= f.label :num_stories, "Number of Stories" %><br>
    <%= f.text_field :num_stories %>
  </div>

  <div>
    <%= f.label :net_lease_area, "Net Lease Area" %><br>
    <%= f.text_field :net_lease_area %>
  </div>

  <div>
    <%= f.label :bldg_class, "Building Class" %><br>
    <%= f.text_field :bldg_class %>
  </div>

  <div>
    <%= f.label :business_park, "Business Park" %><br>
    <%= f.text_field :business_park %>
  </div>

  <div>
    <%= f.label :submarket, "Submarket" %><br>
    <%= f.collection_select( :submarket, @submarkets, :name, :name) %>
  </div>

  <div>
    <%= f.label :landlord_broker_company, "Landlord Broker Company" %><br>
    <%= f.text_field :landlord_broker_company %>
  </div>

  <div>
    <%= f.label :bldg_owner, "Building Owner" %><br>
    <%= f.text_field :bldg_owner %>
  </div>

  <div>
    <%= f.label :property_manager, "Property Manager" %><br>
    <%= f.text_field :property_manager %>
  </div>

  <div>
    <%= f.label :quoted_rate, "Quoted Rate" %><br>
    <%= f.text_field :quoted_rate %>
  </div>

    <div>
    <%= f.label :nnn, "NNN" %><br>
    <%= f.text_field :nnn %>
  </div>

    <div>
    <%= f.label :electric, "Electric" %><br>
    <%= f.text_field :electric %>
  </div>

<br>
<br>
  <div class="actions">
    <%= f.submit %>
  </div>



<% end %>

market_knowledge/app/views/properties/edit.html.erb
<h1>Edit Property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'List', properties_path %>

market_knowledge/app/views/properties/index.html.erb
<h1>All Properties</h1>
<%= link_to 'New Property', new_property_path %>
<br><br>
<%=link_to 'Export to CSV', properties_path(format: 'csv')%>
<br><br>
<%= form_tag import_properties_path, multipart: true do%>
  <%= file_field_tag :file %>
  <%= submit_tag 'Import CSV'%>
<% end %>
<br><br>
<%= form_tag properties_search_path, :method => "get" do %>
<%= label_tag(:search, "Search by Property Name:") %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag("Search", :name => nil) %>
<%end%>
<br><br>

<%= form_tag properties_filter_path, :method => "get" do %>
<%= label_tag(:filter_sub, "Filter by Submarket:") %>
<%= collection_select :property, :submarket, Property.all, :submarket, :submarket %>
<%= submit_tag("Filter") %>
<%end%>
<br><br>
<button><%= link_to 'Reset', properties_path %></button>
<br><br>
<ul>
<% @properties.each do |property| %>
  <li><strong>Name:</strong> <%= property.property_name %> <br><strong>Street:</strong> <%= property.street %> <br><strong>Submarket:</strong> <%= property.submarket %> <br><strong>Class:</strong> <%= property.bldg_class %> <br>   <%= link_to "Show", property_path(property.id) %>  </li>
<% end %>
</ul>

market_knowledge/app/views/properties/new.html.erb
<h1>Create a Property</h1>

<%= render 'form' %>
<br>
<br>
<br>
<%= link_to 'Back to List', properties_path %>

<div id="propertyName">
  <ul>
  </ul>
</div>

market_knowledge/app/views/properties/show.html.erb
<h1> <%= @property.property_name %> </h1>
<h3><u>Address</u></h3>
<p><strong>Street:</strong> <%= @property.street %></p>
<p><strong>City:</strong> <%= @property.city %></p>
<h3><u>Building Info</u></h3>
<p><strong>Year Built:</strong> <%= @property.year_built %></p>
<p><strong>Remodel Year:</strong> <%= @property.remodel_year %></p>
<p><strong>Gross Building Area:</strong> <%= @property.gross_bldg_area %></p>
<p><strong>Foundation Area:</strong> <%= @property.foundation_area %></p>
<p><strong>Number of Stories:</strong> <%= @property.num_stories %></p>
<p><strong>Net Lease Area:</strong> <%= @property.net_lease_area %></p>
<p><strong>Building Class:</strong> <%= @property.bldg_class %></p>
<p><strong>Business Park:</strong> <%= @property.business_park %></p>
<p><strong>Submarket:</strong> <%= @property.submarket %></p>
<p><strong>Landlord Broker Company:</strong> <%= @property.landlord_broker_company %></p>
<p><strong>Building Owner:</strong> <%= @property.bldg_owner %></p>
<p><strong>Property Manager:</strong> <%= @property.property_manager %></p>
<h3><u>Financial Info</u></h3>
<p><strong>Quoted Rate:</strong> <%= @property.quoted_rate %></p>
<p><strong>NNN:</strong> <%= @property.nnn %></p>
<p><strong>Electric:</strong> <%= @property.electric %></p>
<br>
<br>
<br>
<%= link_to 'List', properties_path %>
<%= link_to 'Edit', edit_property_path(@property) %>
<%= link_to 'Destroy', property_path(@property), method: :delete, data: { confirm: 'Are you sure you want to delete?' }%>
<%# need to build this %>
<a href="#" class="js-list" data-id="<%=@property.id%>">Show Leases</a>

<div id="leaseName">
  <ul>

  </ul>
</div>