market_knowledge/config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"
  get "/signin", to: "sessions#new"
  post "/sessions/create", to: "sessions#create"
  delete "/signout", to: "sessions#destroy"

  get "/properties/filter", to: "properties#filter"
  get "properties/search", to: "properties#search"

  get "/leases/filter", to: "leases#filter"
  get "/leases/search", to: "leases#search"

  resources :users
  resources :properties do
    collection {post :import}
  end
  resources :leases do
    collection {post :import}
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

market_knowledge/app/controllers/leases_controller.rb
class LeasesController < ApplicationController
  
    def show
      @lease = Lease.find(params[:id])
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @lease}
      end
    end
  
    def index
      @leases = Lease.all
      respond_to do |format|
        format.html
        format.csv { send_data @leases.to_csv(['tenant'])}
      end   
    end

    def search
      @leases = Lease.search(params[:search])
      render :index
    end

    def filter
      parameters = {
        submarket: params[:submarket],
        lease_high: params[:lease_high],
        lease_low: params[:lease_low],
        lcd_high: params[:lcd_high],
        lcd_low: params[:lcd_low],
        lxd_high: params[:lxd_high],
        lxd_low: params[:lxd_low] 
      }
      @leases = Lease.filter(parameters)
      render :index 
    end

    def import
      Lease.import(params[:file])
      # need to handle failures
      redirect_to leases_url, notice: 'Leases Uploaded successfully'
    end
  
    def new
      @lease = Lease.new
      @properties = Property.all
    end
  
    def create
      @property = Property.find(params[:lease][:property_id])

      params[:lease][:landlord_broker_company] = @property[:landlord_broker_company]
      params[:lease][:bldg_owner] = @property[:bldg_owner]
      params[:lease][:property_manager] = @property[:property_manager]
      params[:lease][:quoted_rate] = @property[:quoted_rate]
      params[:lease][:nnn] = @property[:nnn]
      params[:lease][:electric] = @property[:electric]
    
      @lease = Lease.new(lease_params)
      if @lease.save
        redirect_to @lease
      else
        @properties = Property.all
        render :new
      end
    end
  
    def edit
      @lease = Lease.find(params[:id])
      @properties = Property.all
    end
  
    def update
      @lease = Lease.find(params[:id])
      if @lease.update(lease_params)
        redirect_to @lease
      else
        render :edit
      end
    end
  
    def destroy
      @lease = Lease.find(params[:id])
      @lease.destroy
      redirect_to leases_path
    end
  
    private
  
    def lease_params
      params.require(:lease).permit(:tenant, :lease_size, :suite, :term, :sign_date, :commencement_date, :expiration_date, :lease_type, :fy_rent, :rent_type, :effective_rent, :escalation, :free_rent, :ti_psf, :transaction_type, :tenant_broker_company, :base_year, :landlord_broker_company, :bldg_owner, :property_manager, :quoted_rate, :nnn, :electric, :property_id)
    end
  
  end

market_knowledge/app/views/leases/_form.html.erb
<%= form_for(@lease) do |f| %>

<% if @lease.errors.any? %>
  <div>
    <h2>There were some errors:</h2>

    <ul>
      <% @lease.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div>
    <%= f.label :tenant, "Tenant Name" %><br>
    <%= f.text_field :tenant %>
  </div>

  <div>
    <%= f.label :property_id, "What Property?" %><br>
    <%= @bldg = f.collection_select(:property_id, @properties, :id, :property_name) %>
  </div>

  <div>
    <%= f.label :lease_size, "Lesase Size" %><br>
    <%= f.text_field :lease_size %>
  </div>

  <div>
    <%= f.label :suite, "Suite" %><br>
    <%= f.text_field :suite %>
  </div>

  <div>
    <%= f.label :term, "Term" %><br>
    <%= f.text_field :term %>
  </div>

  <div>
    <%= f.label :sign_date, "Sign Date" %><br>
    <%= f.date_field :sign_date %>
  </div>

  <div>
    <%= f.label :commencement_date, "Commencement Date" %><br>
    <%= f.date_field :commencement_date %>
  </div>

  <div>
    <%= f.label :expiration_date, "Expiration Date" %><br>
    <%= f.date_field :expiration_date %>
  </div>

  <div>
    <%= f.label :lease_type, "Lease Type" %><br>
    <%= f.text_field :lease_type %>
  </div>

  <div>
    <%= f.label :fy_rent, "First Year Rent" %><br>
    <%= f.text_field :fy_rent %>
  </div>

  <div>
    <%= f.label :rent_type, "Rent Type" %><br>
    <%= f.text_field :rent_type %>
  </div>

  <div>
    <%= f.label :effective_rent, "Effective Rent" %><br>
    <%= f.text_field :effective_rent %>
  </div>

  <div>
    <%= f.label :escalation, "Escalation" %><br>
    <%= f.text_field :escalation %>
  </div>

  <div>
    <%= f.label :free_rent, "Months of Free Rent" %><br>
    <%= f.text_field :free_rent %>
  </div>

  <div>
    <%= f.label :ti_psf, "TI per SQFT" %><br>
    <%= f.text_field :ti_psf %>
  </div>

  <div>
    <%= f.label :transaction_type, "Transaction Type" %><br>
    <%= f.text_field :transaction_type %>
  </div>

<br>
<br>
  <div>
    <%= f.submit %>
  </div>

<% end %>

market_knowledge/app/views/leases/edit.html.erb
<h1>Edit Lease</h1>

<%= render 'form' %>

<%= link_to 'Show', @lease %> |
<%= link_to 'List', leases_path %>

market_knowledge/app/views/leases/index.html.erb
<h1>All Leases</h1>

<%= link_to 'New Lease', new_lease_path %>
<br><br>
<%=link_to 'Export to CSV', leases_path(format: 'csv')%>
<br><br>
<%= form_tag import_leases_path, multipart: true do%>
  <%= file_field_tag :file %>
  <%= submit_tag 'Import CSV'%>
<% end %>
<br><br>
<%= form_tag leases_search_path, :method => "get" do %>
<%= label_tag(:search, "Search by Tenant Name:") %>
<%= text_field_tag :search, params[:search] %>
<%= submit_tag("Search", :name => nil) %>
<%end%>
<br><br>
<%= form_tag leases_filter_path, :method => "get" do %>
<%= label_tag(:filter, "Filter by Submarket:") %>
<%= collection_select :submarket, :submarket, Property.all, :submarket, :submarket %>
<br><br>
<%= label_tag(:lease_low, "Lease Size Low:") %>
<%= text_field_tag :lease_low, params[:lease_low] %>
<%= label_tag(:lease_high, "Lease Size High:") %>
<%= text_field_tag :lease_high, params[:lease_high] %>
<br><br>
<%= label_tag(:lcd_low, "LCD Start:") %>
<%= date_field_tag :lcd_low, params[:lcd_low] %>
<%= label_tag(:lcd_high, "LCD End:") %>
<%= date_field_tag :lcd_high, params[:lcd_high] %>
<br><br>
<%= label_tag(:lxd_low, "LXD Start:") %>
<%= date_field_tag :lxd_low, params[:lxd_low] %>
<%= label_tag(:lxd_high, "LXD End:") %>
<%= date_field_tag :lxd_high, params[:lxd_high] %>

<%= submit_tag("Filter") %>
<%end%>
<br><br>
<button><%= link_to 'Reset', leases_path %></button>
<br><br>


<ul>
<% @leases.each do |lease| %>
  <li><strong>Tenant:</strong><%= lease.tenant %><br>
  <li><strong>Bldg:</strong><%= lease.property.property_name %><br>
  <li><strong>Term:</strong><%= lease.term %><br>
  <li><strong>Com. Date:</strong><%= lease.commencement_date %><br>
  <li><strong>FY Rent:</strong><%= lease.fy_rent %><br>
  <li><strong>Rent Type:</strong><%= lease.rent_type %><br>
  <li><strong>Escalation:</strong><%= lease.escalation %><br>
  <li><strong>Free Rent:</strong><%= lease.free_rent %><br>
  <li><strong>TI per SQFT:</strong><%= lease.ti_psf %><br>
  <li><strong>Lease Size:</strong><%= lease.lease_size %><br>
   <%= link_to "Show", lease_path(lease.id) %>  </li>
<% end %>
</ul>

market_knowledge/app/views/leases/new.html.erb
  
<h1>Create a Lease</h1>

<%= render 'form' %>
<br>
<br>
<br>
<%= link_to 'Back to List', leases_path %>

market_knowledge/app/views/leases/show.html.erb
<h3><u>Tenant</u></h3> <%= @lease.tenant %>
<h3><u>Property</u></h3> <%= @lease.property.property_name %>
<h3><u>Lease Details</u></h3>
<p><strong>Lease Size:</strong> <%= @lease.lease_size %></p>
<p><strong>Suite:</strong> <%= @lease.suite %></p>
<p><strong>Term:</strong> <%= @lease.term %></p>
<p><strong>Sign Date:</strong> <%= @lease.sign_date %></p>
<p><strong>Commencement Date:</strong> <%= @lease.commencement_date %></p>
<p><strong>Expiration Date:</strong> <%= @lease.expiration_date %></p>
<p><strong>Lease Type:</strong> <%= @lease.lease_type %></p>
<p><strong>First Year Rent:</strong> <%= @lease.fy_rent %></p>
<p><strong>Rent Type:</strong> <%= @lease.rent_type %></p>
<p><strong>Effective Rent:</strong> <%= @lease.effective_rent %></p>
<p><strong>Escalation:</strong> <%= @lease.escalation %></p>
<p><strong>Months of Free Rent:</strong> <%= @lease.free_rent %></p>
<p><strong>TI per SQFT:</strong> <%= @lease.ti_psf %></p>
<p><strong>Transaction Type:</strong> <%= @lease.transaction_type %></p>
<p><strong>Tenant Broker Company:</strong> <%= @lease.tenant_broker_company %></p>
<p><strong>Base Year:</strong> <%= @lease.base_year %></p>
<h3><u>Building Info</u></h3>
<p><strong>Landlord Broker Company:</strong> <%= @lease.landlord_broker_company %></p>
<p><strong>Building Owner:</strong> <%= @lease.bldg_owner %></p>
<p><strong>Property Manager:</strong> <%= @lease.property_manager %></p>
<p><strong>Quoted Rate:</strong> <%= @lease.quoted_rate %></p>
<p><strong>NNN:</strong> <%= @lease.nnn %></p>
<p><strong>Electric:</strong> <%= @lease.electric %></p>

<br>
<%= link_to 'List', leases_path %>
<%= link_to 'Edit', edit_lease_path(@lease) %>
<%= link_to 'Destroy', lease_path(@lease), method: :delete, data: { confirm: 'Are you sure you want to delete?' }%>

<%# need to build this %>
<a href="#" class="js-more" data-id="<%=@lease.id%>">Show More</a> 


<div class="lease">
  <ul>

  </ul>
</div>